[tool.black]
line-length = 119

[project]
name = "claude-code-gpt-5"
version = "0.3.3"
description = "Connect Claude Code CLI to GPT-5"
readme = "README.md"

requires-python = ">=3.8.1,<4.0.0"
dependencies = [
    "litellm[proxy]!=1.77.3",  # https://github.com/BerriAI/litellm/issues/14762
]

[project.optional-dependencies]
langfuse = [
    "langfuse>=2.0.0,<3.0.0",
]
dev = [
    "black",
    "pre-commit",
    "pylint",
]
